[[containerImages]]
name = "container-base"
tags = [ "latest" ]

[[containerImages]]
name = "macos-cross-compiler-builder"
tags = [ "latest" ]

[[containerImages]]
name = "amuse-lang-environment"
tags = [ "rust-compiler", "llvmenv-jit", "llvmenv", "latest" ]

[[containerImages]]
name = "rustaceans"
tags = [ "jit", "latest" ]

[[containerImages]]
name = "develop-environment"
tags = [ "rustaceans-jit", "rustaceans", "jit", "gitpod", "latest" ]