name: build
description: A command-line application to build container images.
version: 1.0.0
repository: https://gitlab.com/LcJuves/podock

environment:
  sdk: ^3.1.0

# Add regular dependencies here.
dependencies:
  args: ^2.4.2
  logging: ^1.2.0
  path: ^1.8.3

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
