#!/bin/sh

PATH="$OSX_CROSS_COMPILER/bin:$PATH" \
    C_INCLUDE_PATH="$OSX_CROSS_COMPILER/SDK/MacOSX${MACOS_SDK_VERSION}.sdk/usr/include" \
    CC="$OSX_CROSS_COMPILER/bin/oa64-clang" \
    CXX="$OSX_CROSS_COMPILER/bin/oa64-clang++" \
    cargo "$@" --target aarch64-apple-darwin
