#!/bin/sh

PATH="$MACOS_CROSS_COMPILER/bin:$PATH" \
    C_INCLUDE_PATH="$MACOS_CROSS_COMPILER/SDK/MacOSX${MACOS_SDK_VERSION}.sdk/usr/include" \
    CC="$MACOS_CROSS_COMPILER/bin/oa64-clang" \
    CXX="$MACOS_CROSS_COMPILER/bin/oa64-clang++" \
    rustc "$@" --target aarch64-apple-darwin
