#!/bin/sh

PATH="$OSX_CROSS_COMPILER/bin:$PATH" \
    C_INCLUDE_PATH="$OSX_CROSS_COMPILER/SDK/MacOSX${MACOS_SDK_VERSION}.sdk/usr/include" \
    CC="$OSX_CROSS_COMPILER/bin/o64-clang" \
    CXX="$OSX_CROSS_COMPILER/bin/o64-clang++" \
    cargo "$@" --target x86_64-apple-darwin
