FROM debian:bookworm-slim
LABEL maintainer='Liangcheng Juves <email@lcjuves.com>'
LABEL org.opencontainers.image.source=https://github.com/LcJuves/podock
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update -y